---
name: kotlint
on:
  pull_request:
    paths:
      - "**/*.kt"
      - .github/workflows/ktlint.yml
jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.2
      - name: ktlint
        uses: fabiocapasso93/gha-kotlin-linter@v1.0
