---
name: Bad bird CI/CD
on:
  pull_request:
    paths:
      - "**/*.kt"
      - .github/workflows/ktlint.yml
jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 Kotlint trigger by a ${{ github.event_name }} from ${{ github.ref }} to master by ${{ github.actor }}"
      - name: checkout
        uses: actions/checkout@v2.3.2
      - name: ktlint
        uses: fabiocapasso93/gha-kotlin-linter@v1.0
